export * from './Typography_variant_body'
export * from './Typography_variant_span'
export * from './Typography_variant_h1'
export * from './Typography_variant_h2'
export * from './Typography_variant_h3'
export * from './Typography_variant_h4'
export * from './Typography_variant_h5'
export * from './Typography_variant_h6'
