export * from './Typography.types'

export * from './Typography_variant_body.types'
export * from './Typography_variant_h1.types'
export * from './Typography_variant_h2.types'
export * from './Typography_variant_h3.types'
export * from './Typography_variant_h4.types'
export * from './Typography_variant_h5.types'
export * from './Typography_variant_h6.types'
export * from './Typography_variant_span.types'

export * from './Typography_color_dark.types'
export * from './Typography_color_purple.types'
export * from './Typography_color_rose.types'
export * from './Typography_color_white.types'
